---

version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: hbpmip/docker-compose-for-ci:17.06-0
    environment:
       - CIRCLECI: true
    steps:
      - setup_remote_docker:
          version: 17.06.0-ce
      - checkout
      - run:
          name: "Install requirements"
          command: |
            docker --version
            docker info
            pre-commit install
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
      - run:
          name: "Start Woken and the Algorithm Factory runtime"
          command: |
            PATH=$PATH:/$HOME/.captain/bin/ ./run.sh
      - run:
          name: "Test the project"
          command: |
            PATH=$PATH:/$HOME/.captain/bin/ ./test.sh
      - run:
          name: "Stop the containers"
          command: |
            PATH=$PATH:/$HOME/.captain/bin/ ./stop.sh
